### ISSUE TITLE
Deep Learning Boxについて

### ISSUE THREAD

**Issue by Shotaro-Yoshinaga** [tamukohlaboratory/aiseminar2019#2]
Deep Learning Boxにインストールされているubuntuのバージョンが知りたいです．
ubuntu 14.04LTS
ubuntu 16.04LTS
ubuntu
このどれかと思われますが，よろしくお願いします．

**Comment by ytbilly3636** [comment]
@Shotaro-Yoshinaga Ubuntu 14.04 LTSです．

**Comment by Shotaro-Yoshinaga** [comment]
ありがとうございました．
