### ISSUE TITLE
【課題3】順伝播，逆伝播，更新のところでエラーが出ました

### ISSUE THREAD

**Issue by natsukishirasawa189** [tamukohlaboratory/aiseminar2019#4]
課題3番のニューラルネットの更新部分でエラーが出て上手くいかないです．
以下エラー文です．

---------------------------------------------------------------------------
InvalidType                               Traceback (most recent call last)
<ipython-input-1-fa905a9ebc42> in <module>()
     48 
     49   # 順伝播，逆伝播，更新
---> 50   opt.update(cls, x, t)
     51 
     52   # 学習中の誤差関数の表示

11 frames
/usr/local/lib/python3.6/dist-packages/chainer/optimizer.py in update(self, lossfun, *args, **kwds)
    862         if lossfun is not None:
    863             use_cleargrads = getattr(self, '_use_cleargrads', True)
--> 864             loss = lossfun(*args, **kwds)
    865             if use_cleargrads:
    866                 self.target.cleargrads()

/usr/local/lib/python3.6/dist-packages/chainer/link.py in __call__(self, *args, **kwargs)
    292             # forward is implemented in the child classes
    293             forward = self.forward  # type: ignore
--> 294         out = forward(*args, **kwargs)
    295 
    296         # Call forward_postprocess hook

/usr/local/lib/python3.6/dist-packages/chainer/links/model/classifier.py in forward(self, *args, **kwargs)
    141         self.accuracy = None
    142 
--> 143         self.y = self.predictor(*args, **kwargs)
    144         self.loss = self.lossfun(self.y, t)
    145         reporter.report({'loss': self.loss}, self)

<ipython-input-1-fa905a9ebc42> in __call__(self, x)
     20 
     21   def __call__(self, x):
---> 22     h = F.relu(self.l1(x))
     23     y = self.l2(h)
     24     return y

/usr/local/lib/python3.6/dist-packages/chainer/link.py in __call__(self, *args, **kwargs)
    292             # forward is implemented in the child classes
    293             forward = self.forward  # type: ignore
--> 294         out = forward(*args, **kwargs)
    295 
    296         # Call forward_postprocess hook

/usr/local/lib/python3.6/dist-packages/chainer/links/connection/linear.py in forward(self, x, n_batch_axes)
    153             in_size = utils.size_of_shape(x.shape[n_batch_axes:])
    154             self._initialize_params(in_size)
--> 155         return linear.linear(x, self.W, self.b, n_batch_axes=n_batch_axes)

/usr/local/lib/python3.6/dist-packages/chainer/functions/connection/linear.py in linear(x, W, b, n_batch_axes)
    306         args = x, W, b
    307 
--> 308     y, = LinearFunction().apply(args)
    309     if n_batch_axes > 1:
    310         y = y.reshape(batch_shape + (-1,))

/usr/local/lib/python3.6/dist-packages/chainer/function_node.py in apply(self, inputs)
    295 
    296         if configuration.config.type_check:
--> 297             self._check_data_type_forward(in_data)
    298 
    299         hooks = chainer.get_function_hooks()

/usr/local/lib/python3.6/dist-packages/chainer/function_node.py in _check_data_type_forward(self, in_data)
    398         in_type = type_check.get_types(in_data, 'in_types', False)
    399         with type_check.get_function_check_context(self):
--> 400             self.check_type_forward(in_type)
    401 
    402     def check_type_forward(self, in_types):

/usr/local/lib/python3.6/dist-packages/chainer/functions/connection/linear.py in check_type_forward(self, in_types)
     27             x_type.ndim == 2,
     28             w_type.ndim == 2,
---> 29             x_type.shape[1] == w_type.shape[1],
     30         )
     31         if type_check.eval(n_in) == 3:

/usr/local/lib/python3.6/dist-packages/chainer/utils/type_check.py in expect(*bool_exprs)
    549         for expr in bool_exprs:
    550             assert isinstance(expr, Testable)
--> 551             expr.expect()
    552 
    553 

/usr/local/lib/python3.6/dist-packages/chainer/utils/type_check.py in expect(self)
    482             raise InvalidType(
    483                 '{0} {1} {2}'.format(self.lhs, self.exp, self.rhs),
--> 484                 '{0} {1} {2}'.format(left, self.inv, right))
    485 
    486 

InvalidType: 
Invalid operation is performed in: LinearFunction (Forward)

Expect: x.shape[1] == W.shape[1]
Actual: 784 != 4

```
# -*- coding: utf-8 -*-

from chainer import links as L
from chainer import functions as F
from chainer import Variable
from chainer import Chain
from chainer import optimizers
from chainer import datasets
from chainer import iterators
import numpy as np
import six

# STEP1: ネットワークの構造を定義する
class MLP(Chain):
  def __init__(self):
    super(MLP, self).__init__()
    with self.init_scope():
      self.l1 = L.Linear(4, 3)
      self.l2 = L.Linear(3, 2)
  
  def __call__(self, x):
    h = F.relu(self.l1(x))
    y = self.l2(h)
    return y

  
# STEP2: ネットワークの最適化手法の選択
mlp = MLP()
cls = L.Classifier(mlp)
opt = optimizers.SGD()
opt.setup(cls)

# STEP3: 学習データの準備
# バッチサイズ100：100種類の入力を一括で処理する
train, test = datasets.get_mnist()
batchsize = 100
train_iter = iterators.SerialIterator(train, batchsize)
test_iter = iterators.SerialIterator(test, batchsize, repeat=False, shuffle=False)


# STEP4: 学習ループ
for i in six.moves.range(0, len(train), batchsize):
  batch = train_iter.next()
  # x: データセットの中から選んできた100個の画像データ
  # t: xのデータに対するラベル情報（「0」なのか「1」なのか...）
  x = Variable(np.asarray([s[0] for s in batch]))
  t = Variable(np.asarray([s[1] for s in batch]))
  
  # 順伝播，逆伝播，更新
  opt.update(cls, x, t)
  
  # 学習中の誤差関数の表示
  if i % 1000 == 0:
    print('loss:', cls.loss.data)
  
  
# STEP5: テストモード
# accuracyというリストにバッチ毎の正解率を追加して最後に平均を取る
# 値の追加はaccuracy.append(0.0)などのようにして行う
# 平均の算出はNumPyの関数np.meanを使う
accuracy = []
for i in six.moves.range(0, len(test), batchsize):
  batch = test_iter.next()
  x = Variable(np.asarray([s[0] for s in batch]))
  t = Variable(np.asarray([s[1] for s in batch]))
  
  # 順伝播，正解率の算出
  cls(x,t)

  # accuracy.append()
  accuracy.append(cls.accuracy.data)

print('accuracy', np.mean(accuracy))
```

**Comment by natsukishirasawa189** [comment]
解決しました．
下記の注意事項を満たしてなかったことが原因だったみたいです．
**入力は784（=28x28）で出力は10にしなければならないことに留意してください．**

L1とL2を次のように変更したら治りました．

```
# STEP1: ネットワークの構造を定義する
class MLP(Chain):
  def __init__(self):
    super(MLP, self).__init__()
    with self.init_scope():
      self.l1 = L.Linear(4, 3)
      self.l2 = L.Linear(3, 2)
  
  def __call__(self, x):
    h = F.relu(self.l1(x))
    y = self.l2(h)
    return y
```
⇓
```
# STEP1: ネットワークの構造を定義する
class MLP(Chain):
  def __init__(self):
    super(MLP, self).__init__()
    with self.init_scope():
      self.l1 = L.Linear(784,100)
      self.l2 = L.Linear(100,10)
  
  def __call__(self, x):
    h = F.relu(self.l1(x))
    y = self.l2(h)
    return y
```

**Comment by ytbilly3636** [comment]
@natsukishirasawa189 Thank you for your contribution!
